### ISSUE TITLE
episodes url don't work

### ISSUE THREAD

**Issue by ghost** [BastienBoymond/VostfreeScrapper#1]
``episodes: [
    { id: '1', link: [Array] },
    { id: '2', link: [Array] },
    { id: '3', link: [Array] },
    { id: '4', link: [Array] },
    { id: '5', link: [Array] },
    { id: '6', link: [Array] },
    { id: '7', link: [Array] },
    { id: '8', link: [Array] },
    { id: '9', link: [Array] },
    { id: '10', link: [Array] },
    { id: '11', link: [Array] },
    { id: '12', link: [Array] },
    { id: '13', link: [Array] }
  ]

**Comment by BastienBoymond** [comment]
[Array] is for said that you got more  than 1 Links
like you got 3 url to see  the episodes

Are you sure this not work ?
